"""Curated event → economics → exposure cards (no generated recommendations)."""


CARDS = [
    {
        "id": "major_averages",
        "icon": "📊",
        "name": "The three big averages",
        "almanac_title": "Ten years on the market calendar",
        "season": "The broad market · always in view",
        "start": None,
        "end": None,
        "lead": "A decade of daily history for the S&P 500, Dow Jones Industrial Average, and NASDAQ Composite.",
        "mechanism": "This is a look back at broad U.S. market indexes, not individual companies or live quotes. The historical changes compare each index with its own earlier closing level; the three index point values are not directly comparable.",
        "research": [
            {"ticker": "", "name": "S&P 500", "why": "Broad large-company index included in the historical series."},
            {"ticker": "", "name": "Dow Jones Industrial Average", "why": "Thirty-company price-weighted index included in the historical series."},
            {"ticker": "", "name": "NASDAQ Composite", "why": "Broad Nasdaq-listed index included in the historical series."},
        ],
        "research_section": "Index history",
        "risks": "These are price indexes and do not include dividends. The index providers restrict redistribution; this self-hosted educational use should remain noncommercial and properly attributed. Historical patterns do not predict future results.",
        "source_keys": ["fred_sp500", "fred_djia", "fred_nasdaq_composite"],
        "metric": "market_averages",
        "wisdom_note": {
            "saying": "“Mr. Market is there to serve you, not to guide you.”",
            "tradition": "Warren Buffett, on Benjamin Graham’s Mr. Market · Berkshire letter, 1987",
            "lesson": "A market price is a quote, not an order. History can be studied without obeying every swing.",
            "url": "https://www.berkshirehathaway.com/letters/1987.html",
        },
        "wisdom_extras": [
            {
                "saying": "A streak feels like a sign; the next draw doesn't remember.",
                "tradition": "Table wisdom · probability lesson, wording by Investor Almanac",
                "lesson": "In games with independent draws, past wins do not change the odds. Markets are not dice, so don't turn a market streak into a law.",
            },
        ],
    },
    {
        "id": "cash",
        "icon": "💵",
        "name": "Cash is paying",
        "almanac_title": "When cash bears fruit",
        "season": "All year",
        "start": None,
        "end": None,
        "lead": "A Treasury bill yield is a useful yardstick for what short-term government debt currently pays.",
        "mechanism": "When short-term yields are higher, holding cash has a return; it also changes the opportunity cost of taking investment risk.",
        "research": [
            {"ticker": "SGOV", "name": "0–3 month Treasury bill ETF", "why": "Holds very short U.S. Treasury bills."},
            {"ticker": "BIL", "name": "1–3 month Treasury bill ETF", "why": "Another short Treasury-bill exposure to compare."},
        ],
        "risks": "A quoted bill yield is not the same as an ETF's return. Fund expenses, distributions, taxes, and market prices differ.",
        "source_keys": ["treasury_bills"],
        "metric": "cash",
        "wisdom_note": {
            "saying": "“Tie it and rely (upon Allah).”",
            "tradition": "Jamiʿ at-Tirmidhi 2517 · Islamic hadith",
            "lesson": "Make sensible preparations, then accept what you cannot control—rather than treating a yield as a guarantee.",
            "url": "https://sunnah.com/tirmidhi:2517",
        },
    },
    {
        "id": "rates",
        "icon": "📈",
        "name": "The yield curve",
        "almanac_title": "When the tide of rates turns",
        "season": "All year",
        "start": None,
        "end": None,
        "lead": "Short and long Treasury rates offer a quick snapshot of borrowing costs across maturities.",
        "mechanism": "Rates influence mortgages, business financing, bond prices, and the relative appeal of cash. Different industries respond in different ways.",
        "research": [
            {"ticker": "SGOV", "name": "T-bills", "why": "Very short Treasury exposure."},
            {"ticker": "SHY", "name": "1–3 year Treasuries", "why": "Short-maturity Treasury exposure."},
            {"ticker": "IEF", "name": "7–10 year Treasuries", "why": "Intermediate Treasury exposure."},
        ],
        "risks": "Yields are not forecasts. Bond prices generally move opposite yields, and longer maturities tend to move more for a given rate change.",
        "source_keys": ["treasury_bills", "treasury_curve"],
        "metric": "curve",
        "wisdom_note": {
            "saying": "“A single tree does not make a forest.”",
            "tradition": "Chinese proverb · English translation; wording varies",
            "lesson": "A portfolio can hold many tickers yet still depend on one industry or the same underlying risk.",
            "url": "https://www.wenlinshe.com/chengyu/du-mu-bu-cheng-lin-041102",
        },
    },
    {
        "id": "back_to_school",
        "icon": "🎒",
        "name": "Back to school",
        "almanac_title": "When the school bell rings",
        "season": "Late summer",
        "start": (7, 15),
        "end": (9, 15),
        "lead": "Late summer brings K–12 school shopping and the start of college move-in season.",
        "mechanism": "Families and schools buy clothing, supplies, computers, and dorm essentials. K–12 Chromebook adoption differs from college students' device choices; the broad retail data cannot separate those buyers.",
        "research": [
            {"ticker": "XLY", "name": "Consumer discretionary ETF", "why": "Broad exposure to discretionary businesses."},
            {"ticker": "AMZN", "name": "Amazon", "why": "Retail and e-commerce exposure."},
            {"ticker": "AAPL", "name": "Apple", "why": "A possible college and education-device connection; not a proxy for all school technology."},
        ],
        "risks": "School calendars vary, purchases may shift between months, and the Census retail categories are not school-specific.",
        "source_keys": ["census_electronics", "census_clothing"],
        "metric": "school",
        "wisdom_note": {
            "saying": "“A journey of a thousand li begins beneath one's feet.”",
            "tradition": "Dàodéjīng, chapter 64 · Chinese classic",
            "lesson": "Start with one clear question: learn what a measure says before deciding what to do with it.",
            "url": "https://taoism.net/tao-te-ching-chapter-64/",
        },
    },
    {
        "id": "holiday_shopping",
        "icon": "🎁",
        "name": "Holiday shopping season",
        "almanac_title": "The winter buying season",
        "season": "November–December",
        "start": (11, 1),
        "end": (12, 31),
        "lead": "Holiday shopping touches stores, e-commerce, delivery networks, and payments.",
        "mechanism": "The Census Bureau's seasonal factors include recurring seasonal, holiday, and trading-day patterns in retail sales. They do not isolate the effect of holiday shopping alone.",
        "research": [
            {"ticker": "XLY", "name": "Consumer discretionary ETF", "why": "Broad consumer-discretionary exposure."},
            {"ticker": "AMZN", "name": "Amazon", "why": "Retail and e-commerce exposure."},
            {"ticker": "UPS", "name": "UPS", "why": "Package transportation exposure."},
            {"ticker": "V", "name": "Visa", "why": "Payment-network exposure."},
        ],
        "risks": "Sales can shift earlier, inflation changes dollar totals, and shipping or payment volume does not translate directly into company profit.",
        "source_keys": ["census_general", "census_nonstore"],
        "metric": "holiday",
        "wisdom_note": {
            "saying": "“Don’t count your chickens before they hatch.”",
            "tradition": "English proverb · traditional wording",
            "lesson": "Busy shopping months do not guarantee bigger profits—or rising investments. Wait for the evidence to arrive.",
        },
    },
    {
        "id": "tax_refunds",
        "icon": "✉️",
        "name": "Tax-refund season",
        "almanac_title": "When refund checks find their way home",
        "season": "Winter into spring · roughly January–April",
        "start": (1, 15),
        "end": (4, 30),
        "lead": "As tax returns are processed, refunds move back into household budgets.",
        "mechanism": "The IRS publishes weekly cumulative refund totals and average refund amounts. A refund may go to spending, savings, or debt; the IRS totals cannot tell us which, and they do not predict market returns.",
        "research": [
            {"ticker": "", "name": "Household spending", "why": "Some refunds may be used for purchases, but the IRS does not report how recipients use them."},
            {"ticker": "", "name": "Savings and debt payments", "why": "Refunds may also be saved or used to pay down debt; those uses are not tracked in this series."},
        ],
        "research_section": "A household cash-flow season",
        "risks": "The IRS filing season opening date shifts from year to year. Cumulative totals are nominal dollars and can change with tax law, filing speed, and the timing of reports. They are not a measure of retail spending.",
        "reference_links": [
            {"title": "IRS · weekly filing-season statistics and CSV", "url": "https://www.irs.gov/newsroom/filing-season-statistics-by-year"},
        ],
        "source_keys": ["irs_filing_stats"],
        "metric": "irs_refunds",
        "wisdom_note": {
            "saying": "Count the refund when it clears.",
            "tradition": "Investor Almanac table wisdom · editor-written",
            "lesson": "A tax refund is money returned to a household, not a bonus guaranteed to be spent.",
        },
    },
    {
        "id": "crop_progress",
        "icon": "🌾",
        "name": "Planting and harvest",
        "almanac_title": "From seedtime to harvest",
        "season": "Growing season · spring through fall",
        "start": (4, 1),
        "end": (11, 30),
        "lead": "Field work has its own calendar: planting, emergence, growing, and harvest arrive at different times for different crops and regions.",
        "mechanism": "USDA’s weekly Crop Progress reports compare national and state crop stages with the previous year and a five-year average. Crop timing and condition can matter to food supply chains, but a crop report alone cannot tell us how prices or company profits will move.",
        "research": [
            {"ticker": "", "name": "Farm inputs and equipment", "why": "Planting conditions can affect demand for seed, fertilizer, machinery, and other farm inputs."},
            {"ticker": "", "name": "Grain handling and storage", "why": "Harvest timing can affect when crops move through storage and transport networks."},
            {"ticker": "", "name": "Food supply chains", "why": "Crop outcomes can affect supply availability, but this report alone does not predict prices or profits."},
        ],
        "research_section": "Field notes, not a harvest forecast",
        "risks": "Reports cover selected crops and regions, rely on survey estimates, and can be revised. Planting and harvest dates vary by crop, weather, and location; this is a broad U.S. calendar, not a local farm forecast.",
        "reference_links": [
            {"title": "USDA · National Crop Progress reports and historical charts", "url": "https://www.nass.usda.gov/Publications/National_Crop_Progress/"},
            {"title": "USDA · Crop Progress survey methods and release schedule", "url": "https://www.nass.usda.gov/Surveys/Guide_to_NASS_Surveys/Crop_Progress_and_Condition/"},
        ],
        "source_keys": [],
        "metric": "seasonal_context",
        "metric_headline": "Weekly reports · April–November",
        "metric_caption": "USDA compares planting and harvest progress with last year and the five-year average. Open the current report for this week’s figures.",
        "wisdom_note": {
            "saying": "“You reap what you sow.”",
            "tradition": "Traditional proverb · wording appears in many cultures",
            "lesson": "A season’s work unfolds over time; one weekly report is only a field note, not the whole harvest.",
        },
    },
    {
        "id": "hurricane_season",
        "icon": "🌀",
        "name": "Hurricane season",
        "almanac_title": "When the coast watches the sky",
        "season": "Atlantic season · June–November",
        "start": (6, 1),
        "end": (11, 30),
        "lead": "Atlantic hurricane season is a recurring weather calendar with real consequences for people, homes, local businesses, and essential services.",
        "mechanism": "NOAA’s 1991–2020 Atlantic average is 14 named storms, 7 hurricanes, and 3 major hurricanes. Activity is most concentrated from mid-August to mid-October, with a climatological peak around September 10. These are basin-wide averages, not a forecast for a particular place or year.",
        "research": [
            {"ticker": "", "name": "Coastal households and businesses", "why": "Storms can directly disrupt homes, local commerce, and essential services."},
            {"ticker": "", "name": "Utilities and transport", "why": "Power, roads, ports, and other infrastructure may be disrupted depending on a storm’s path."},
            {"ticker": "", "name": "Property insurance", "why": "Claims and exposure vary by location and policy; this is context, not a trade signal."},
        ],
        "research_section": "Preparedness and community impact",
        "risks": "Storm risk is highly location-specific, and historical averages are not a forecast. The card does not turn damage or disruption into a beneficiary trade; people and community safety come first.",
        "reference_links": [
            {"title": "NOAA · Atlantic hurricane climatology", "url": "https://www.nhc.noaa.gov/climo/"},
            {"title": "NOAA · current tropical cyclone advisories", "url": "https://www.nhc.noaa.gov/"},
        ],
        "source_keys": [],
        "metric": "seasonal_context",
        "metric_headline": "14 named storms · 7 hurricanes · 3 major",
        "metric_caption": "NOAA Atlantic basin averages for 1991–2020 · most activity is usually mid-August to mid-October.",
        "wisdom_note": {
            "saying": "When the wind rises, check the moorings first.",
            "tradition": "Investor Almanac table wisdom · editor-written",
            "lesson": "Preparation protects people and property. A storm’s path and impact can’t be inferred from the season alone.",
        },
    },
    {
        "id": "medicare_enrollment",
        "icon": "🗓️",
        "name": "Medicare open enrollment",
        "almanac_title": "A fall checkup for next year’s coverage",
        "season": "Every fall · October 15–December 7",
        "start": (10, 15),
        "end": (12, 7),
        "lead": "Each fall, people with Medicare can review and change health and prescription-drug coverage for the coming year.",
        "mechanism": "Plan benefits, costs, and provider networks can change. The annual window is a meaningful household decision season, but enrollment dates do not predict healthcare-company or market performance.",
        "research": [
            {"ticker": "", "name": "Medicare plan choices", "why": "People can compare coverage, provider networks, premiums, and out-of-pocket costs for the coming year."},
            {"ticker": "", "name": "Prescription coverage", "why": "Drug formularies and cost-sharing can change between plan years."},
            {"ticker": "", "name": "Healthcare providers", "why": "Networks and access can vary by plan and location."},
        ],
        "research_section": "A yearly household decision",
        "risks": "Coverage needs and plan availability differ by person and location. This is general calendar context, not insurance guidance or an investment recommendation.",
        "reference_links": [
            {"title": "CMS · Medicare open enrollment dates and guidance", "url": "https://www.cms.gov/priorities/key-initiatives/medicare-open-enrollment-partner-resources"},
        ],
        "source_keys": [],
        "metric": "seasonal_context",
        "metric_headline": "October 15 – December 7",
        "metric_caption": "Annual Medicare window to review or change health and prescription-drug coverage for next year.",
        "wisdom_note": {
            "saying": "“A stitch in time saves nine.”",
            "tradition": "Traditional English proverb",
            "lesson": "Review the details before the deadline; coverage choices are personal and local.",
        },
    },
    {
        "id": "winter_heating",
        "icon": "🔥",
        "name": "Heating season",
        "almanac_title": "Keep an eye on the hearth",
        "season": "October–March",
        "start": (10, 1),
        "end": (3, 31),
        "lead": "Residential natural-gas use generally climbs when colder weather brings heating demand.",
        "mechanism": "EIA reports residential consumption, which includes heating plus cooking, water heating, and other household uses. Weather is a major driver, but not the only one.",
        "research": [
            {"ticker": "XLU", "name": "Utilities ETF", "why": "Broad utility-sector exposure."},
            {"ticker": "XLE", "name": "Energy ETF", "why": "Broad energy-sector exposure, including some natural-gas producers."},
        ],
        "risks": "Warm winters, regional fuel mixes, storage, supply, and regulated utility pricing can change how demand affects businesses.",
        "source_keys": ["eia_residential_gas"],
        "metric": "heating",
        "wisdom_note": {
            "saying": "“A warm hearth begins with a watchful eye.”",
            "tradition": "Investor Almanac field note · editor-written",
            "lesson": "Seasonal gas use reflects weather and household needs; it does not predict an energy investment’s return.",
        },
    },
    {
        "id": "summer_driving",
        "icon": "🚙",
        "name": "Summer driving",
        "almanac_title": "The open-road season",
        "season": "May–September",
        "start": (5, 1),
        "end": (9, 30),
        "lead": "EIA's weekly gasoline product-supplied series is one indicator of fuel moving into the U.S. market.",
        "mechanism": "More driving can raise gasoline use, while prices, inventories, refining, imports, and the economy also shape the data.",
        "research": [
            {"ticker": "XLE", "name": "Energy ETF", "why": "Broad energy-sector exposure."},
            {"ticker": "MPC", "name": "Marathon Petroleum", "why": "Refining and fuel-marketing exposure."},
            {"ticker": "VLO", "name": "Valero Energy", "why": "Refining exposure."},
        ],
        "risks": "Product supplied is a demand proxy, not a direct count of miles driven; refinery margins and crude prices matter too.",
        "source_keys": ["eia_gasoline"],
        "metric": "driving",
        "wisdom_note": {
            "saying": "“The road is long; check the miles and the fuel.”",
            "tradition": "Investor Almanac field note · editor-written",
            "lesson": "A demand measure is only one marker along the road; prices and margins matter too.",
        },
    },
    {
        "id": "home_garden",
        "icon": "🪴",
        "name": "Home and garden projects",
        "almanac_title": "As the garden wakes",
        "season": "Spring",
        "start": (3, 1),
        "end": (6, 30),
        "lead": "Building-material and garden-equipment sales follow a seasonal pattern as outdoor projects return.",
        "mechanism": "The Census series tracks sales at building-material and garden-equipment stores. It does not say whether a sale was for a renovation, a new home, or a landscaping project.",
        "research": [
            {"ticker": "XHB", "name": "Homebuilders ETF", "why": "Broad housing and building-industry exposure."},
            {"ticker": "HD", "name": "Home Depot", "why": "Home-improvement retail exposure."},
            {"ticker": "LOW", "name": "Lowe's", "why": "Home-improvement retail exposure."},
        ],
        "risks": "Mortgage rates, home prices, weather, and household confidence can outweigh seasonal timing.",
        "source_keys": ["census_building"],
        "metric": "home",
        "wisdom_note": {
            "saying": "“As the garden grows, so do the errands.”",
            "tradition": "Investor Almanac field note · editor-written",
            "lesson": "Seasonal store sales can hint at activity, but they do not identify profits or future returns.",
        },
    },
    {
        "id": "work_stoppages",
        "icon": "✊",
        "name": "When work stops",
        "almanac_title": "When the workbench goes quiet",
        "season": "People and production",
        "start": None,
        "end": None,
        "lead": "Large strikes and lockouts are moments when workers, employers, and communities negotiate over pay and working conditions.",
        "mechanism": "A work stoppage can interrupt production or services and shift costs among workers, employers, suppliers, and customers. BLS monthly measures cover stoppages involving at least 1,000 workers; they are a narrow window into a much wider labor story.",
        "research": [
            {"ticker": "XLI", "name": "Industrials ETF", "why": "Broad exposure to industrial companies, some of which employ large workforces."},
            {"ticker": "IYT", "name": "Transportation ETF", "why": "Exposure to transportation businesses where labor availability can affect operations."},
        ],
        "risks": "These monthly series are not a count of all labor disputes, union membership, wage growth, or company-level impact. They are released with a lag, and a stoppage can affect firms in very different ways.",
        "source_keys": ["bls_work_stoppages"],
        "metric": "labor",
        "wisdom_note": {
            "saying": "“Every work stoppage has people on both sides of the ledger.”",
            "tradition": "Investor Almanac field note · editor-written",
            "lesson": "Production and costs matter, but so do workers, families, and communities.",
        },
    },
    {
        "id": "public_trade_filings",
        "icon": "🗂️",
        "name": "Follow the public trade filings",
        "almanac_title": "Follow the paper trail",
        "season": "Paper trail · all year",
        "start": None,
        "end": None,
        "lead": "A few famous names draw attention, but the fine print matters: different filers report different things, and a disclosure is never a ready-made trade signal.",
        "mechanism": "SEC Form 4 reports cover corporate officers, directors, and large shareholders; transaction codes distinguish open-market purchases and sales from grants, option exercises, gifts, and other events. House and Senate Periodic Transaction Reports cover certain reportable transactions by members and other covered filers, and may include spouse or dependent transactions.",
        "research": [
            {"ticker": "", "name": "Corporate insider Forms 4", "why": "Reports can identify transactions by officers, directors, and large shareholders."},
            {"ticker": "", "name": "Congressional transaction reports", "why": "House and Senate disclosures cover certain reportable transactions, often with delays and value ranges."},
            {"ticker": "", "name": "Institutional 13F snapshots", "why": "Quarterly holdings reports show a partial, delayed view of some large managers’ portfolios."},
        ],
        "research_section": "Official filing searches",
        "reference_links": [
            {"title": "SEC · latest Form 4 ownership filings", "url": "https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=4&company=&dateb=&owner=only&count=40"},
            {"title": "House · financial disclosure reports and PTRs", "url": "https://disclosures-clerk.house.gov/FinancialDisclosure"},
            {"title": "Senate · public financial disclosures", "url": "https://efdsearch.senate.gov/search/home/"},
            {"title": "OGE · officials’ public financial disclosures", "url": "https://www.oge.gov/web/oge.nsf/Officials%20Individual%20Disclosures%20Search%20Collection?OpenForm="},
            {"title": "SEC · how to read Forms 3, 4, and 5", "url": "https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins-69"},
        ],
        "filing_highlights": [
            {"title": "Pelosi household · House PTR example", "detail": "A January 2025 report lists spouse-owned GOOGL and AMZN call-option purchases, with value ranges—not exact totals. It is a delayed household disclosure, not a current position.", "url": "https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2025/20026590.pdf"},
            {"title": "Donald Trump · 2026 OGE annual report", "detail": "A public financial disclosure reports assets and income; an annual report is not a live stock-trade feed.", "url": "https://www2.oge.gov/web/oge.nsf/Resources/Now%2BAvailable%3A%2BThe%2BPresident%E2%80%99s%2Band%2BVice%2BPresident%E2%80%99s%2Bcertified%2Bannual%2Bfinancial%2Bdisclosure%2Breports"},
            {"title": "BlackRock · SEC 13F holdings search", "detail": "Institutional holdings are periodic snapshots. They do not show a live portfolio, every transaction, or the manager’s reason for holding a security.", "url": "https://www.sec.gov/edgar/search/#/q=BlackRock%252C%2520Inc.&forms=13F-HR"},
        ],
        "risks": "Filings can arrive after a trade; congressional disclosures may be filed up to 45 days later and often report value ranges rather than exact amounts. Form 4s include transactions that are not open-market buys or sells. Annual reports, periodic transaction reports, Form 4s, and 13F holdings each describe different things; none reveals the filer’s full reasoning or guarantees a current position.",
        "source_keys": [],
        "metric": "public_filings",
        "wisdom_note": {
            "saying": "“Don’t bet the hand before you’ve seen the cards.”",
            "tradition": "Investor Almanac table wisdom · editor-written",
            "lesson": "A headline is only a hint. Open the filing and check who reported what, when, and under which form.",
        },
    },
    {
        "id": "canada_energy",
        "icon": "🛢️",
        "name": "The northern energy corridor",
        "almanac_title": "A current from the north",
        "season": "Neighbors and trade",
        "start": None,
        "end": None,
        "lead": "The U.S. and Canada are linked by a large cross-border flow of crude oil and petroleum products.",
        "mechanism": "EIA's monthly net-import series offers one measurable thread in that relationship: the balance of petroleum moving from Canada into the U.S. Trade ties can shape supply options, infrastructure use, and regional energy markets.",
        "research": [
            {"ticker": "XLE", "name": "Energy ETF", "why": "Broad exposure to U.S. energy companies, with varied links to Canadian supply and trade."},
            {"ticker": "AMLP", "name": "Energy infrastructure ETF", "why": "Exposure to some pipeline and midstream businesses that move energy across regions."},
        ],
        "risks": "Net imports are not a measure of total trade or a forecast. Prices, pipeline capacity, refinery configuration, policy, and events elsewhere can matter more; these ETFs do not track the trade series.",
        "source_keys": ["eia_canada_oil"],
        "metric": "canada_energy",
        "wisdom_note": {
            "saying": "“A border may divide the map; a supply chain crosses it.”",
            "tradition": "Investor Almanac field note · editor-written",
            "lesson": "Trade flows connect regions, but one monthly series cannot tell the whole story.",
        },
    },
    {
        "id": "energy_industry",
        "icon": "⚡",
        "name": "Energy: fuels and the supply chain",
        "almanac_title": "Where the fuel winds blow",
        "season": "Global benchmarks · always relevant",
        "start": None,
        "end": None,
        "lead": "Crude oil and natural gas prices are different market signals, and neither tells the whole story of an energy company.",
        "mechanism": "Higher crude benchmarks can lift upstream producers' sales prices, but also raise feedstock costs for refiners and fuel bills for households. Refiners depend on the spread between product and crude prices; pipelines depend more on throughput and contracts. Henry Hub is a U.S. gas benchmark, while regional prices can differ.",
        "research": [
            {"ticker": "XLE", "name": "Energy sector ETF", "why": "Mostly large energy producers and service companies; not a pure oil-price tracker."},
            {"ticker": "AMLP", "name": "Energy infrastructure ETF", "why": "Pipeline and midstream exposure with different drivers from producers."},
            {"ticker": "CRAK", "name": "Refiners ETF", "why": "Refining exposure where product margins can matter more than crude direction."},
        ],
        "risks": "Benchmark prices are nominal and do not measure company costs, hedges, volumes, regulation, debt, or profit. Oil and gas prices can move in opposite directions.",
        "source_keys": ["eia_wti", "eia_brent", "eia_henry_hub"],
        "metric": "energy_benchmarks",
        "wisdom_note": {
            "saying": "“A barrel’s price is one line on a much larger ledger.”",
            "tradition": "Investor Almanac field note · editor-written",
            "lesson": "Costs, contracts, production, and margins shape what a benchmark means to a business.",
        },
    },
    {
        "id": "renewable_power",
        "icon": "🌞",
        "name": "Renewables: sun, wind, and water",
        "almanac_title": "When sun and wind fill the grid",
        "season": "Powering the year · all seasons",
        "start": None,
        "end": None,
        "lead": "EIA tracks how much U.S. electricity comes from renewable sources, month by month.",
        "mechanism": "The series combines utility-scale renewable generation with estimated small-scale solar. It includes wind, solar, conventional hydropower, geothermal, and biomass—so it is an industry-wide measure, not a pure wind-or-solar gauge.",
        "research": [
            {"ticker": "ICLN", "name": "Global clean energy ETF", "why": "A broad thematic fund with international holdings and exposure to several clean-energy businesses."},
            {"ticker": "TAN", "name": "Solar ETF", "why": "More concentrated exposure to solar-related companies."},
            {"ticker": "FAN", "name": "Wind energy ETF", "why": "Focused exposure to wind-energy companies."},
        ],
        "research_section": "Possible exposure paths",
        "risks": "More renewable electricity does not guarantee profits for manufacturers, utilities, or project owners. Interest rates, equipment costs, grid connections, curtailment, policy, and competition all matter; the latest observations can be preliminary.",
        "source_keys": ["eia_renewable_power"],
        "metric": "renewable_power",
        "wisdom_note": {
            "saying": "“The grid keeps score one kilowatt-hour at a time.”",
            "tradition": "Investor Almanac field note · editor-written",
            "lesson": "Generation is a useful measure of activity, not a guarantee of company earnings.",
        },
    },
    {
        "id": "precious_metals",
        "icon": "🥇",
        "name": "Gold and silver",
        "almanac_title": "Gold in the hills, silver in the wires",
        "season": "Precious metals · always relevant",
        "start": None,
        "end": None,
        "lead": "Gold and silver share a precious-metal label, but silver also has substantial industrial uses.",
        "mechanism": "Gold is often watched alongside real interest rates, currencies, and demand for stores of value. Silver combines investment demand with industrial uses in electronics, solar, and manufacturing, so economic activity can matter more. Miners add operating, labor, and jurisdiction risks beyond metal prices.",
        "research": [
            {"ticker": "GLD", "name": "Gold trust", "why": "Designed to reflect gold bullion less expenses; it is not a mining company."},
            {"ticker": "SLV", "name": "Silver trust", "why": "Designed to reflect silver bullion less expenses."},
            {"ticker": "GDX", "name": "Gold miners ETF", "why": "Mining-company shares add business and equity-market risks to gold exposure."},
        ],
        "risks": "The World Bank monthly benchmark series is not a live quote. Funds have fees and tracking differences; miners are not equivalent to physical metal.",
        "source_keys": ["worldbank_metals"],
        "metric": "precious_metals",
        "wisdom_note": {
            "saying": "“All that glisters is not gold.”",
            "tradition": "William Shakespeare · The Merchant of Venice, Act 2, scene 7",
            "lesson": "A shiny price chart is not a value estimate. A rising price alone cannot tell us whether gold is overvalued.",
            "url": "https://www.folger.edu/explore/shakespeares-works/the-merchant-of-venice/read/2/7/",
        },
        "wisdom_extras": [
            {
                "saying": "“The 170,000 tons of gold will be unchanged in size and still incapable of producing anything.”",
                "tradition": "Warren Buffett · Berkshire shareholder letter, 2011",
                "lesson": "One investor’s argument, not a verdict: gold can store value, but unlike a business it produces no cash flow.",
                "url": "https://www.berkshirehathaway.com/letters/2011ltr.pdf",
            },
        ],
    },
    {
        "id": "conflict_watch",
        "icon": "🕊️",
        "name": "Conflict watch",
        "almanac_title": "When headlines shake the map",
        "season": "War and its human cost · always relevant",
        "start": None,
        "end": None,
        "lead": "Current conflict-related reporting changes over time, so this note follows the latest headlines instead of assuming the same wars will always be in focus.",
        "mechanism": "War first harms people and essential services. Depending on the place and event, wider costs can reach food and energy buyers, airlines, shipping, local businesses, public budgets, and families forced to move.",
        "research": [
            {"ticker": "", "name": "People and essential services", "why": "Deaths, displacement, damaged homes, and interrupted food, water, health care, and education are the direct human costs."},
            {"ticker": "", "name": "Businesses and households", "why": "The reported location and event determine whether costs flow through fuel, shipping, food, tourism, insurance, or disrupted work."},
        ],
        "research_section": "Who may face costs or disruption",
        "risks": "Headlines are not a complete or independently verified conflict database. Economic channels are possibilities, not measured losses or forecasts; no investment is a direct proxy for war.",
        "reference_links": [],
        "source_keys": ["bbc_conflict_news"],
        "metric": "conflict_context",
        "wisdom_note": {
            "saying": "“When war enters the ledger, count the human cost first.”",
            "tradition": "Investor Almanac field note · editor-written",
            "lesson": "People and essential services come before any discussion of economic effects.",
        },
    },
]
